

if object_id(dbo.vw_GetTabularScoringAVGSDataGeneric) is not null
	drop view dbo.vw_GetTabularScoringAVGSDataGeneric




CREATE	VIEW [dbo].[vw_GetTabularScoringAVGSDataGeneric] 
AS
    SELECT 
         r.EventID as EventID
        ,et.Day1or2 as Day1or2
        ,et.EventTurnID as EventTurnID
        ,[Criteria_1]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_1')
        ,[Criteria_1_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_1')
        ,[Criteria_2]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_2')
        ,[Criteria_2_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_2')
        ,[Criteria_3]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_3')
        ,[Criteria_3_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_3')
        ,[Criteria_4]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_4')
        ,[Criteria_4_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_4')
        ,[Criteria_5]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_5')
        ,[Criteria_5_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_5')
        ,[Criteria_6]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_6')
        ,[Criteria_6_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_6')
        ,[Criteria_7]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_7')
        ,[Criteria_7_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_7')
        ,[Criteria_8]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_8')
        ,[Criteria_8_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_8')
        ,[Criteria_9]        = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_9')
        ,[Criteria_9_Exec]   = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_9')
        ,[Criteria_10]       = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_10')
        ,[Criteria_10_Exec]  = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_10')
        ,[Criteria_11]       = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_11')
        ,[Criteria_11_Exec]  = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_11')
        ,[Criteria_12]       = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_12')
        ,[Criteria_12_Exec]  = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_12')
        ,[Criteria_13]       = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_13')
        ,[Criteria_13_Exec]  = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_13')
        ,[Criteria_14]       = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_14')
        ,[Criteria_14_Exec]  = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_14')
        ,[Criteria_15]       = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_15')
        ,[Criteria_15_Exec]  = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_15')
        ,[Criteria_16]       = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_16')
        ,[Criteria_16_Exec]  = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_16')
        ,[Criteria_17]       = (SELECT     AVG(etjs.Score) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_17')
        ,[Criteria_17_Exec]  = (SELECT AVG(etjs.Execution) FROM tblEventTurnJudge etj INNER JOIN tblEventTurnJudgeScores etjs ON etj.EventTurnJudgeID = etjs.EventTurnJudgeID INNER JOIN tblJudgingCriteria jc ON etjs.JudgingCriteriaID = jc.JudgingCriteriaID WHERE etj.EventTurnID = et.EventTurnID AND jc.PivotColumnMapping = 'Criteria_17')
   
        FROM tblEventTurns et
        INNER JOIN tblRegistrationDivisions rd
            ON et.RegistrationDivisionID = rd.RegistrationDivisionID
        INNER JOIN tblRegistrations r
            on rd.RegistrationID = r.RegistrationID   



-- grant execute on vw_GetTabularScoringAVGSDataGeneric to myUser
